import queue
import threading
from typing import Optional, Sequence
import ollama
from ollama import ChatResponse
from loguru import logger

from glados.config import GladosConfig
from plugins.plugin_manager import PluginManager

plugin_manager = PluginManager()


class LLMClient:
    def __init__(self, url: str, model: str, headers: Optional[dict] = None, config: GladosConfig = None):
        """
        Initializes an LLM client for interacting with Ollama.

        Args:
            url (str): Base URL for the Ollama API.
            model (str): Model name to query (e.g., "llama" or "vicuna").
            headers (dict): Optional headers for API requests.
            config (GladosConfig): Configuration object for the LLMClient.
        """
        self.url = url
        self.model = model
        self.headers = headers or {}
        self.functions = {}
        self.client = ollama.Client()  # Synchronous client for threading

        # Queues for communication
        self.llm_queue: queue.Queue[str] = queue.Queue()
        self.tts_queue: queue.Queue[str] = queue.Queue()

        # Initialize personality preprompts
        self._messages = []
        for line in config.personality_preprompt:
            self._messages.append(
                {"role": list(line.keys())[0], "content": list(line.values())[0]}
            )

        # Lock for thread-safe access to messages
        self._lock = threading.Lock()

    @property
    def messages(self) -> Sequence[dict[str, str]]:
        with self._lock:
            return self._messages.copy()

    def chat(self, content: str) -> str:
        """
        Communicates with the LLM model using the provided content.
        Handles tool calls if the model invokes them.

        Args:
            content (str): The user input to the model.

        Returns:
            str: The response generated by the model.
        """
        with self._lock:
            self._messages.append({"role": "user", "content": content})

        logger.info(f"User input: {content}")
        logger.info(f"Available plugins/tools: {plugin_manager.get_available_plugins_as_list()}")

        # Query the LLM
        response: ChatResponse = self.client.chat(
            self.model,
            messages=self.messages,
            tools=plugin_manager.get_available_plugins_as_list()
            # stream=True
        )

        tool_result = None

        try:
            if response.message.tool_calls:
                # Handle tool calls in the response
                for tool in response.message.tool_calls:
                    if function_to_call := plugin_manager.get_available_plugins().get(tool.function.name):
                        logger.info(f"Executing tool: {tool.function.name} with args: {tool.function.arguments}")
                        tool_result = function_to_call(**tool.function.arguments)
                        logger.info(f"Tool output: {tool_result}")

                        # Add tool result to messages
                        with self._lock:
                            self._messages.append({
                                "role": "tool",
                                "name": tool.function.name,
                                "content": str(tool_result),
                            })
                    else:
                        logger.warning(f"Tool {tool.function.name} not found.")
        except Exception as e:
            logger.error(f"Error: {e}")

        # If no tool was used, handle the direct response
        if response.message.content and not tool_result:
            direct_response = response.message.content.strip()
            logger.info(f"Direct LLM response: {direct_response}")

            with self._lock:
                self._messages.append({"role": "assistant", "content": direct_response})

            # Add to TTS queue only, avoid re-queueing to LLM queue
            self.tts_queue.put(direct_response)

        # Query the LLM again if a tool was used to finalize the interaction
        if tool_result:
            logger.info("Querying LLM again after tool use.")
            try:
                final_response: ChatResponse = self.client.chat(
                    self.model,
                    messages=self.messages,
                )
                final_content = final_response.message.content.strip()
                logger.info(f"Final LLM response after tool use: {final_content}")

                with self._lock:
                    self._messages.append({"role": "assistant", "content": final_content})

                # Add to TTS queue only
                self.tts_queue.put(final_content)

            except Exception as e:
                logger.error(f"Error during final LLM query: {e}")

        # Signal end of stream for TTS
        self.tts_queue.put("<EOS>")
        logger.info("Chat complete.")

        # Return the last response for logging or display purposes
        with self._lock:
            return self._messages[-1]["content"]

