import sounddevice as sd
from kokoro_onnx import Kokoro

# Initialize the Kokoro model
kokoro = Kokoro("../models/kokoro-82m-onnx/model.onnx", "voices.json")

# Generate audio
text = "Hello! This audio is generated by kokoro."
voice = "af_sarah"  # Choose a voice from voices.json
speed = 1.0         # Adjust speed
lang = "en-us"      # Language code

samples, sample_rate = kokoro.create(text, voice=voice, speed=speed, lang=lang)

# Play the audio
print("Playing audio...")
sd.play(samples, sample_rate)
sd.wait()
