import json
from typing import Dict, Optional

from loguru import logger

from glados.config import GladosConfig


class ContextManager:
    _instance = None  # Singleton instance

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(ContextManager, cls).__new__(cls)
            cls._instance._initialized = False  # Prevent multiple initializations
        return cls._instance

    def __init__(self):
        if self._initialized:
            logger.error("ContextManager is not initialized")
            return  # Skip re-initialization
        logger.warning("Deprecated, please remove")
        self.contexts: Dict[str, Dict] = {}  # Store contexts and their histories
        self.active_task: Optional[str] = None  # Tracks the current active context

    def __enter__(self):
        if not self.active_task:
            raise ValueError("No active task to manage. Use 'start_new_activity' to create one.")
        logger.info(f"Entering context for task: '{self.active_task}'")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        logger.info(f"Exiting context for task: '{self.active_task}'")
        self.active_task = None

    def configure(self, config: GladosConfig):
        try:
            for ctx in config.contexts:
                self.start_new_activity(ctx)
        except Exception as e:
            logger.error("Unable to initialize contexts")

    def start_new_activity(self, task_name: str):
        """
        Start a new task or activity in a context.
        :param task_name: Name of the task to start.
        """
        task_name = task_name.lower()
        if task_name in self.contexts:
            logger.info(f"Context '{task_name}' already exists. Switching to it.")
        else:
            self.contexts[task_name] = {"history": [], "tool_outputs": {}}
            logger.info(f"Started a new task: '{task_name}'.")
        self.active_task = task_name

    def switch_to_activity(self, task_name: str):
        """
        Switch to an existing task.
        :param task_name: Name of the task to switch to.
        """
        task_name = task_name.lower()
        if task_name not in self.contexts:
            raise ValueError(f"Task '{task_name}' does not exist. Start it first.")
        self.active_task = task_name
        logger.success(f"Switched to task: '{task_name}'.")

    def add_message(self, role: str, content: str):
        """
        Add a message to the active task's history.
        :param role: Role in the conversation ('user' or 'assistant' or 'tool').
        :param content: Message content.
        """
        if not self.active_task:
            raise ValueError("No active task to add a message to.")
        self.contexts[self.active_task]["history"].append({"role": role, "content": content})

    def add_tool_output(self, tool_name: str, output: str):
        """
        Add tool output to the active task.
        :param tool_name: Name of the tool.
        :param output: Output generated by the tool.
        """
        if not self.active_task:
            raise ValueError("No active task to add tool output to.")
        self.contexts[self.active_task]["history"].append({"role": 'tool', "name": tool_name, "content": output})

    def get_task_context(self) -> str:
        """
        Get the current task's context as a string to send to the LLM.
        """
        if not self.active_task:
            raise ValueError("No active task to get context from.")
        task = self.contexts[self.active_task]
        history = "\n".join([f"{msg['role']}: {msg['content']}" for msg in task["history"]])
        tool_context = "\n".join([f"{tool}: {output}" for tool, output in task["tool_outputs"].items()])
        return f"Task: {self.active_task}\nHistory:\n{history}\nTool Outputs:\n{tool_context}"

    def save_contexts(self, file_path: str):
        """
        Save all contexts to a JSON file.
        :param file_path: Path to the file.
        """
        with open(file_path, "w") as file:
            json.dump(self.contexts, file, indent=4)
        logger.success(f"Contexts saved to '{file_path}'.")

    def load_contexts(self, file_path: str):
        """
        Load contexts from a JSON file.
        :param file_path: Path to the file.
        """
        with open(file_path, "r") as file:
            self.contexts = json.load(file)
        logger.success(f"Contexts loaded from '{file_path}'.")


# Example usage
if __name__ == "__main__":
    context_manager = ContextManager()

    # Start and switch tasks
    context_manager.start_new_activity("cooking")
    context_manager.add_message("user", "How do I make pasta?")
    context_manager.add_message("assistant", "Boil water, add pasta, and cook for 8-10 minutes.")
    context_manager.add_tool_output("recipe_search", "Pasta Carbonara Recipe")

    with context_manager:
        print(context_manager.get_task_context())

    context_manager.start_new_activity("music")
    context_manager.add_message("user", "Play some relaxing music.")
    with context_manager:
        print(context_manager.get_task_context())

    context_manager.switch_to_activity("cooking")
    with context_manager:
        print(context_manager.get_task_context())

    # Save and load tasks
    context_manager.save_contexts("contexts.json")
    context_manager.load_contexts("contexts.json")
